[project]
name = "npu-design"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "onnx>=1.23.0",
    "pandas>=3.0.6",
    "thop>=0.1.1.post2209072238",
    "torch>=2.14.0",
]

[project.scripts]
npu-design = "npu_design:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
